FROM node:20-bullseye

WORKDIR	/app

COPY	*.json ./
COPY	vite.config.ts ./
COPY	tsconfig*.json ./


RUN		apt-get update && apt-get install -y python3 make g++ \
    &&	npm install

COPY	public/ ./public/
COPY	src/ ./src/
COPY	index.html ./index.html

# RUN		npm run build
CMD ["npm", "run", "build", "--", "--watch"]
