services:
  app:
    build: ../backend/
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ../database:/data
      - shared_frontend:/app/public/dist
      - ../backend/uploads:/app/uploads
    env_file:
      - ".env"
    depends_on:
      - frontend

  frontend:
    build: ../frontend/
    container_name: frontend
    volumes:
      - shared_frontend:/app/dist
      # Ajout des dossiers important au front. On pourra tej pour la correction
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    environment:
      # Surveille les changement dans les fichiers typescript
      - CHOKIDAR_USEPOLLING=true
      # Surveille les changement dans les autres fichiers
      - WATCHPACK_POLLING=true
volumes:
  shared_frontend:
