

services:
  app:
    build: ../backend/
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    container_name: fastify-volume-container

  postgres:
    build: ../database/
    container_name: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/va/lib/postresql/data

volumes:
  postgres_data:


