

services:
  app:
    build: ../backend/
    container_name: fastify
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public

  postgres:
    build: ../database/
    container_name: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/va/lib/postresql/data

volumes:
  postgres_data:


