
services:
  app:
    build: ../backend/
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ../database:/data
      - shared_frontend:/app/public/dist
      - ../backend/uploads:/app/uploads
    env_file:
      - ".env"
    depends_on:
    - frontend

  frontend:
    build: ../frontend/
    container_name: frontend
    volumes:
    - shared_frontend:/app/dist


volumes:
  shared_frontend: