services:
  blockchain:
    build: ../blockchain/
    container_name: blockchain
    ports:
      - "8545:8545"
    volumes:
      - blockchain_state:/blockchain/state
      - blockchain_deployment:/blockchain/deployment
    healthcheck:
      test: ["CMD", "cast", "client", "--rpc-url", "http://localhost:8545"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: ../backend/
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ../database:/data
      - shared_frontend:/app/public/dist
      - ../backend/uploads:/app/uploads
      - blockchain_deployment:/blockchain/deployment:ro
    env_file:
      - ".env"
    environment:
      - BLOCKCHAIN_RPC_URL=http://blockchain:8545
    depends_on:
      blockchain:
        condition: service_healthy
      frontend:
        condition: service_started

  frontend:
    build: ../frontend/
    container_name: frontend
    volumes:
      - shared_frontend:/app/dist
      # Ajout des dossiers important au front. On pourra tej pour la correction
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    environment:
      # Surveille les changement dans les fichiers typescript
      - CHOKIDAR_USEPOLLING=true
      # Surveille les changement dans les autres fichiers
      - WATCHPACK_POLLING=true
volumes:
  shared_frontend:
  blockchain_state:
  blockchain_deployment:
