

services:
  app:
    build: ../backend/
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend/public:/app/public
      - ../database:/data
    env_file:
      - ".env"


